version: '3.8'
services:
  my_todo:
    restart: always #docker重启时候，容器也重启
    build: #构建docker镜像
      context: ./ #Dockerfile 文件的目录
      dockerfile: Dockerfile #Dockerfile 文件的名称
    image: my_todo:1.0.0 #镜像名称和版本号
    container_name: my_todo1.0.1 #容器名称
    ports: # 宿主机和容器之间映射端口
      - 8888:8888

  mysql:
    image: mysql
    restart: always
    container_name: todo_mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456