### 待办任务周期总览
# 根据日期查询这个日期某个周期类型的待办事项，返回结果优先级高的在前 ，
# 周期类型有cycle_type 1日，2周，3月，4年
# 没传指定日期，默认当前时间的某个周期
# GET http://127.0.0.1:8888/statisView/<cycle_type>/<date>

### 1 查询 2023-04-19 这一天的 待办任务总览
GET http://127.0.0.1:8888/statisView/1/2023-04-19

### 2 查询 2023-03-19 这一周的 待办任务总览
GET http://127.0.0.1:8888/statisView/2/2023-03-19

### 3 查询 当前调用时间 这一月的 待办任务总览
GET http://127.0.0.1:8888/statisView/3

### 4 查询 当前调用时间 这一年的 待办任务总览
GET http://127.0.0.1:8888/statisView/4